// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Platforms.Mac.Views;
using MvvMCross.Core.ViewModels;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Mac.Presenters.Attributes;

namespace MvvmCross.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxContentPresentation(WindowIdentifier = "WindowController")]
    public partial class SecondView : MvxViewController<SecondViewModel>
    {
        public SecondView(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var set = this.CreateBindingSet<SecondView, SecondViewModel>();
            set.Bind(GoBackButton).To(vm => vm.NavigateToFirstViewCommand);
            set.Apply();
        }
    }
}
