// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Platforms.Mac.Views;
using MvvmCross.Platforms.Mac.Presenters.Attributes;
using MvvmCross.Presenters;
using MvvmCross.Presenters.Attributes;
using MvvmCross.ViewModels;
using MvvMCross.Core.ViewModels;

namespace MvvmCross.Mac
{
	[MvxFromStoryboard("Main")]
	public partial class WindowController : MvxWindowController
	{
		public WindowController (IntPtr handle) : base (handle)
		{
		}
    }
}
